-- This code was generated by ChatGPT

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity clock_div_tb is
end clock_div_tb;

architecture behavior of clock_div_tb is

    -- Component Declaration for the Unit Under Test (UUT)
    component clock_div
        port (
            clk         : in std_ulogic;
            rst         : in std_ulogic;
            base_period : in unsigned(7 downto 0);
            clk_b0125   : out std_ulogic;
            clk_b025    : out std_ulogic;
            clk_b05     : out std_ulogic;
            clk_b1      : out std_ulogic;
            clk_b2      : out std_ulogic
        );
    end component;

    -- Signals for UUT connections
    signal clk         : std_ulogic := '0';
    signal rst         : std_ulogic := '0';
    signal base_period : unsigned(7 downto 0) := (others => '0');
    signal clk_b0125   : std_ulogic;
    signal clk_b025    : std_ulogic;
    signal clk_b05     : std_ulogic;
    signal clk_b1      : std_ulogic;
    signal clk_b2      : std_ulogic;

    -- Clock period for simulation
    constant clk_period : time := 20 ns; -- 50 MHz clock

begin

    -- Instantiate the Unit Under Test (UUT)
    uut: clock_div
        port map (
            clk         => clk,
            rst         => rst,
            base_period => base_period,
            clk_b0125   => clk_b0125,
            clk_b025    => clk_b025,
            clk_b05     => clk_b05,
            clk_b1      => clk_b1,
            clk_b2      => clk_b2
        );

    -- Clock generation process
    clk_process : process
    begin
        while true loop
            clk <= '0';
            wait for clk_period / 2;
            clk <= '1';
            wait for clk_period / 2;
        end loop;
    end process;

    -- Stimulus process to test the design
    stim_proc: process
    begin
        -- Test 1: Reset the design
        rst <= '1';
        wait for 100 ns;
        rst <= '0';
        wait for 100 ns;

        -- Test 2: Apply base period and observe clock outputs
        base_period <= to_unsigned(5, 8); -- Example base period
        wait for 500 us; -- Wait for some clock cycles to observe behavior

        -- You can apply additional test cases here, adjusting base_period
        base_period <= to_unsigned(10, 8);
        wait for 500 us;

        -- Stop the simulation
        wait;
    end process;

end architecture behavior;
-- End ChatGPT code